title: Paper Review
description: My Personal Stack Problems
author: Eunjo Jang
github: https://github.com/eunjo99
about: AI Researcher | Data Scientist | Recommendation System
disqus_shortname: paperreviews
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jangeunjo/"
    - icon: fa-github
      link: "https://github.com/eunjo99"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://eunjo99.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
